#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check1102="11.2,11.02"
CHECK_TITLE_check1102="[check1102] Ensure no Elasticsearch Domains allow ingress from 0.0.0.0/0 (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_check1102="NOT_SCORED"
CHECK_TYPE_check1102="CUSTOM"
CHECK_ALTERNATE_check1102="check1102"

check1102(){

for regx in $REGIONS; do
    LIST_OF_ES_DOMAINS=$($AWSCLI es list-domain-names --query 'DomainNames[*]' $PROFILE_OPT --region $regx --output text)
    if [[ $LIST_OF_ES_DOMAINS ]];then
        while read -r DOMAIN;do
            SG=$($AWSCLI es describe-elasticsearch-domain-config --domain-name $DOMAIN --query 'DomainConfig.VPCOptions.Options.SecurityGroupIds' $PROFILE_OPT --region $regx --output text)

	    SG_MATCH=$($AWSCLI ec2 describe-security-groups --group-ids $SG --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort<=`443` && ToPort>=`443`)) && contains(IpRanges[].CidrIp, `0.0.0.0/0`)]) > `0`].{GroupId:GroupId}' $PROFILE_OPT --region $regx --output text)

	    if [[ $SG_MATCH ]];then

               textFail "Found Elasticsearch Domain: $DOMAIN open to 0.0.0.0/0 via Security Group $SG in Region $regx" "$regx"

	   else

	       textPass "Elasticsearch Domain: $DOMAIN not open to 0.0.0.0/0" "regx"

            fi

        done <<< "$LIST_OF_ES_DOMAINS"
    fi

done
}
